import { normalizeDatabaseUrl, createLocalDatabaseClient, asDrizzleTable } from '@astrojs/db/runtime';
import '@astrojs/db/dist/runtime/virtual.js';

const dbUrl = normalizeDatabaseUrl(":memory:", "file:///home/admiralcapo/personal/edge-talk-astro/.astro/content.db");
const db = createLocalDatabaseClient({ dbUrl, enableTransactions: false });

const Negotiations = asDrizzleTable("Negotiations", {"columns":{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Negotiations","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Negotiations","primaryKey":false,"optional":false}},"created_at":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"created_at","collection":"Negotiations"}},"updated_at":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"updated_at","collection":"Negotiations"}}},"deprecated":false,"indexes":{}}, false);
const Sessions = asDrizzleTable("Sessions", {"columns":{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Sessions","primaryKey":true}},"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Sessions","primaryKey":false,"optional":false}},"nId":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"nId","collection":"Sessions","primaryKey":false,"optional":false,"references":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Negotiations","primaryKey":true}}}},"qna":{"type":"json","schema":{"optional":false,"unique":false,"deprecated":false,"name":"qna","collection":"Sessions"}},"chatHistory":{"type":"json","schema":{"optional":false,"unique":false,"deprecated":false,"name":"chatHistory","collection":"Sessions"}},"created_at":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"created_at","collection":"Sessions"}},"updated_at":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"updated_at","collection":"Sessions"}}},"deprecated":false,"indexes":{}}, false);

export { Negotiations as N, Sessions as S, db as d };
